### PR TITLE
Change SSH command for Windows compatibility

### PR DESCRIPTION
**Pull request by ben221199**
Windows cannot handle the `<<` very well, so this pull request will change the command that is executed, so that it is Windows compatible.

### CODE REVIEW

**Comment by freekmurze** [comment]
It seems like this breaks the tests. 

Could you also make sure that this fix is applied for windows?

I've not seen too many complaints about incompatibilities. In which versions of Windows is this not working for which commands?

**Comment by ben221199** [comment]
It didn't work on Windows 10 on my laptop. I will take a look at the tests.

**Comment by ben221199** [comment]
I see why they broke, your tests also check on commands with `<<`.

**Comment by ben221199** [comment]
I improved some things. I moved the earlier code to the `fix-windows-old` branch. The current code now should work on both and does work with `<<`.

**Comment by freekmurze** [comment]
The snapshots indicate that only the quotes have changed. 

I think all the code changes are not needed. Could you start from the old code and add the quotes there?

**Comment by ben221199** [comment]
Okay, I tried some things for hours, but I think that how it is implemented now, with `bash -se` isn't the best way. I would suggest to do it like the following:
```
$input = new InputStream();
$proc = Process::fromShellCommandline('ssh -i id_rsa root@mydomain.com bash');
$proc->setInput($input);
$proc->start();
$input->write('whoami'."\n");
$input->write('whoami'."\n");
$input->close();
$proc->wait();

echo 'OUT '.$proc->getOutput();
```

Output:
```
OUT root
root

```

**Comment by ben221199** [comment]
Rewrote the pull request to implement my last suggestion.

**Comment by freekmurze** [comment]
I've decided not to pull this in for now. This package has been downloaded half a million times without this problem coming up. I'm afraid that changing things now, will lead to more problems. 

In your project, extend the SSH class and overwrite the `getExecuteCommand` to get the behaviour you want.

**Comment by ben221199** [comment]
Okay, but hopefully it works for people that come across #41.

**Pull request closed without merging**
