### PR TITLE
Prevent asking to add to known_hosts

### LINKED ISSUE #13: Prevent asking to add to known_hosts
Hi there,

The SSH command only connects when the host is added to the local known_hosts file. When I connect to a server for the first time it will not work.

When I use the following options with the command it will work.
```
-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
```

References:
- https://linux.die.net/man/1/ssh
- https://www.unix.com/man-page/osx/1/ssh/
- https://superuser.com/questions/141344/dont-add-hostkey-to-known-hosts-for-ssh#answer-1013998

### PR DESCRIPTION
**Pull request by linuxjuggler**
This PR should close #13 once it is merged.

* [x] fix the tests

PS: I am not with such thing, it is better for the user to use [ssh-keyscan](https://linux.die.net/man/1/ssh-keyscan) on his local machine before using the package.

### CODE REVIEW

**Comment by owenvoke** [comment]
Would it be worth adding a property and method to toggle this? e.g.
```php
private bool $strictHostKeyChecking;

public function enableStrictHostKeyChecking(): self
{
    $this->strictHostKeyChecking = true;

    return $this;
}

// in getExtraOptions()
if (! $this->strictHostKeyChecking) {
    $extraOptions[] = "-o StrictHostKeyChecking=no",
    $extraOptions[] = "-o UserKnownHostsFile=/dev/null",
}
```

**Comment by linuxjuggler** [comment]
I like that this way they can either have or not.

**Comment by linuxjuggler** [comment]
Since someone else decided to submit a different version, I think no need to keep this one open.

**Comment by freekmurze** [comment]
Still thank you for your work!

**Comment by linuxjuggler** [comment]
thanks @freekmurze

**Pull request closed without merging**
