### PR TITLE
ssh-keyscan & known_hosts file 

### PR DESCRIPTION
**Pull request by hyperized**
In reference to #17.

Ended up creating the KnownHosts class to manage file existence and allow new host entries to be made. It will accept a custom location if the regular `~/.ssh/known_hosts` is not an option (distributed systems).

Tried to stay away from further library dependencies, but this code is tied to the posix extension, which is enabled by default by PHP (https://www.php.net/manual/en/posix.installation.php).

The code is a bit rough, and I suppose not completely up to your style, but please let me know if and how you want this code adjusted.

### CODE REVIEW

**Comment by freekmurze** [comment]
The permissions stuff makes this package kinda complicated. Is this really necessary? Couldn't we bail out by saying in the readme that the authorized_keys file should exists and the permissions set up correctly?

**Comment by freekmurze** [comment]
@hyperized Looking at this code, I don't know if the problem raised in #17 is solved. When somebody connects to a host and the hostkey is changed, it should fail. Right now that changed hostkey is added to `known_hosts`.

**Comment by freekmurze** [comment]
It seems like these changes are not working at all. When removing my `authorized_keys` file and using this code to connect to a server, it will ask interactively if a connection should be made.

image

I'm currently considering just removing all the code around keyscan in favour of making the package simple again.

**Comment by hyperized** [comment]
Just to clarify, authorized_keys and known_hosts are two different things. I can put this in a separate package if you don’t want/need it.

**Comment by freekmurze** [comment]
O, I meant to say `known_hosts`. Updated that in my previous comment.

**Comment by hyperized** [comment]
Ok, I been re-reading this and I'm confused. Normally when I do a PR it's not merged unless it's done, reviewed and 100% functional. I was asking for code specific feedback and instead it's merged.

Now that said, I understand you aim for simplicity, should I just make a new package for this specific functionality?

**Comment by freekmurze** [comment]
> Normally when I do a PR it's not merged unless it's done, reviewed and 100% functional.

Normally I do this too, but in this case it's fine because the `v2` branch is unreleased and this is the only feature being added.

> Now that said, I understand you aim for simplicity, should I just make a new package for this specific functionality?
OK!

**Pull request merged**
